name: Benchmarks

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  phpbench:
    name: "PHPBench"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.2"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"

      - name: Run performance benchmarks
        run: |
          vendor/bin/phpbench run tests/Benchmark/Performance --report=aggregate

      - name: Check JSON serialiser memory leaks
        run: |
          vendor/bin/phpbench run tests/Benchmark/Memory/Json* --report=memory --iterations=1

      - name: Check XML serialiser memory leaks
        run: |
          vendor/bin/phpbench run tests/Benchmark/Memory/Xml* --report=memory --iterations=1
